Task 2.2 done
YahorLukyanchyk/inno-php-trainee pull request #6
Opened 2023-04-19 15:29 UTC by YahorLukyanchyk

2023-04-20 10:21 UTC, vovakovalchukk requested changes

2023-04-25 12:13 UTC, vovakovalchukk requested changes

2023-04-26 15:51 UTC, vovakovalchukk requested changes

2023-04-26 15:51 UTC, vovakovalchukk commented on app/controllers/UserController.php
> -        $user = User::getUserById($this->routeParams['id']);
параметры лучше всего напрямую передовать в аргументах метода, чтобы можно было писать максимально контролируемый код

2023-04-26 15:51 UTC, vovakovalchukk commented on app/controllers/UserController.php
> +        if ((filter_var($userData['email'], FILTER_VALIDATE_EMAIL)) && (preg_match("/^[a-zA-Zа-яёА-ЯЁ]+$/u", $userData['name']))) {
мы должны обработать все ошибки, обрабатывать успех нет смысла, как и в if else, достаточно только if для ошибки

2023-04-26 15:51 UTC, vovakovalchukk commented on app/controllers/UserController.php
> +        $user = User::get($this->routeParams['id']);
договорились же разделять логику отступами

2023-04-26 15:51 UTC, vovakovalchukk commented on app/controllers/UserController.php
> +        $userData = (array)json_decode(file_get_contents('php://input'));
договорились же разделять логику отступами

2023-04-26 23:27 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> +        $user = User::get($this->routeParams['id']);
исправил

2023-04-26 23:27 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> +        $userData = (array)json_decode(file_get_contents('php://input'));
исправил

2023-04-27 00:27 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> +        if ((filter_var($userData['email'], FILTER_VALIDATE_EMAIL)) && (preg_match("/^[a-zA-Zа-яёА-ЯЁ]+$/u", $userData['name']))) {
исправил обработку ошибок и сделал вывод сообщения об ошибке на странице + чтобы одинаково выводилось описал запрос post в файле postData.js

2023-04-27 00:40 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> -        $user = User::getUserById($this->routeParams['id']);
не уверен что правильно понял, но я вынес $this->routeParams['id'] в отдельную переменную $id и уже ее передаю в качестве аргумента

2023-04-27 07:21 UTC, vovakovalchukk requested changes

2023-04-27 07:21 UTC, vovakovalchukk commented on app/controllers/UserController.php
> +        $user = User::get($id);
Здесь имелось ввиду передача аргумента именно в метод show()

2023-04-27 07:21 UTC, vovakovalchukk commented on app/controllers/UserController.php
> +        }
где отступ

2023-04-27 07:21 UTC, vovakovalchukk commented on app/controllers/UserController.php
> +            exit("Your name does not match a valid pattern");
почему здесь отступ есть, а в таком же примере кода выше нет? весь код должен быть одного стиля

2023-04-27 16:00 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> +            exit("Your name does not match a valid pattern");
исправил

2023-04-27 16:00 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> +        }
исправил

2023-04-27 16:02 UTC, YahorLukyanchyk commented on app/controllers/UserController.php
> +        $user = User::get($id);
не уверен в правильности, но параметр id в случае, если он есть, я отправляю на уровне Router'a, а если его нет, то просто вызываю метод контроллера без параметров во избежание ошибок в тех методах, где id не используется

2023-05-06 19:39 UTC, merged